### ISSUE TITLE
关于tomcat服务

### ISSUE THREAD

**Issue by Vector6662** [czwbig/mini-spring#3]
请问大佬，本项目需要启动本地的tomcat服务器吗？如果不需要，请问启动项目后这个报错您有遇到过吗？

```
严重: Unknown default host [localhost] for service [StandardService[Tomcat]]. Tomcat will not be able process HTTP/1.0 requests that do not specify a host name.
```

**Comment by czwbig** [comment]
本项目需要启动本地的tomcat服务器吗？ 不需要，项目内嵌了 tomcat，跟你启动 spring boot 不需要外置 tomcat 服务器一样。  
这个提示应该是你环境有问题，例如本机 hosts 配置是否正确？检查运行环境是否能正确解析 localhost

**Comment by Vector6662** [comment]
谢谢大佬的回答！
